# Generated by Django 4.2.26 on 2025-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition_based__attendance_system_app', '0002_students_section_alter_dataset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(default='A', max_length=4),
        ),
    ]
