# Generated by Django 4.2.26 on 2025-11-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition_based__attendance_system_app', '0003_alter_students_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='section',
        ),
    ]
