# Generated by Django 4.2.27 on 2026-01-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition_based__attendance_system_app', '0004_remove_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
